package Project;

import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mes dossiers
 */
public class codeFrame extends javax.swing.JFrame {
 private int  xMouse;
 private int yMouse;
    /**
     * Creates new form codeFrame
     */
    public codeFrame() {
        initComponents();
         ImageIcon menu=new ImageIcon(getClass().getResource("/world.png"));
             this.setIconImage (menu.getImage());
             this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit = new javax.swing.JLabel();
        defaultJl = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        jpw = new javax.swing.JPasswordField();
        okBut = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 617));
        setUndecorated(true);
        getContentPane().setLayout(null);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExitSimple.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitMouseReleased(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(936, 0, 30, 30);

        defaultJl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defaultsimple.png"))); // NOI18N
        defaultJl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        defaultJl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                defaultJlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                defaultJlMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                defaultJlMouseReleased(evt);
            }
        });
        getContentPane().add(defaultJl);
        defaultJl.setBounds(897, 0, 30, 30);

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        getContentPane().add(FrameDrag);
        FrameDrag.setBounds(-2, 5, 980, 40);

        Text.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 255, 255));
        Text.setText("Entrez un code pour jouer  :");
        getContentPane().add(Text);
        Text.setBounds(370, 200, 300, 30);

        jpw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpwMouseClicked(evt);
            }
        });
        jpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpwActionPerformed(evt);
            }
        });
        getContentPane().add(jpw);
        jpw.setBounds(410, 260, 170, 30);

        okBut.setText("Ok");
        okBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButActionPerformed(evt);
            }
        });
        getContentPane().add(okBut);
        okBut.setBounds(460, 330, 45, 23);
        getContentPane().add(icon);
        icon.setBounds(590, 260, 34, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeBackground.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 980, 617);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        // TODO add your handling code here:
      int x=evt.getXOnScreen();
     int y=evt.getYOnScreen();
    this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        // TODO add your handling code here:
         xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed

    private void okButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButActionPerformed
        // TODO add your handling code here:
         char[] p = jpw.getPassword();
         String str= new String (p);
         
          if (str.equals("test")){
              this.setVisible(false);
        new NiveauJFrame().setVisible(true); 
          }else {
              ImageIcon II=new ImageIcon(getClass().getResource("/32.png"));
             icon.setIcon (II);
              
          }
    }//GEN-LAST:event_okButActionPerformed

    private void jpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpwActionPerformed
        // TODO add your handling code here:
     char[] p = jpw.getPassword();
         String str= new String (p);
        
          if (str.equals("test")) {
              this.setVisible(false);
        new NiveauJFrame().setVisible(true); 
          }else {
              ImageIcon II=new ImageIcon(getClass().getResource("/32.png"));
             icon.setIcon (II);
              
          }
    }//GEN-LAST:event_jpwActionPerformed

    private void jpwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpwMouseClicked
        // TODO add your handling code here:
        jpw.setText("");
    }//GEN-LAST:event_jpwMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered

        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/exitnt.png"));
        Exit.setIcon(exitIcon);
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited

        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/ExitSimple.png"));
        Exit.setIcon(exitIcon);
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseReleased
        System.exit(0);
    }//GEN-LAST:event_ExitMouseReleased

    private void defaultJlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaultJlMouseEntered
        // TODO add your handling code here:
        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/defaultIN.png"));
        defaultJl.setIcon(exitIcon);
    }//GEN-LAST:event_defaultJlMouseEntered

    private void defaultJlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaultJlMouseExited
        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/defaultsimple.png"));
        defaultJl.setIcon(exitIcon);
    }//GEN-LAST:event_defaultJlMouseExited

    private void defaultJlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaultJlMouseReleased
        this.setExtendedState(MenuJFrame.ICONIFIED);
    }//GEN-LAST:event_defaultJlMouseReleased

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel defaultJl;
    private javax.swing.JLabel icon;
    private javax.swing.JPasswordField jpw;
    private javax.swing.JButton okBut;
    // End of variables declaration//GEN-END:variables
}
