package Project;


import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mes dossiers
 */
public class MenuJFrame extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
   

    /**
     * Creates new form NewJFrame
     */
    public MenuJFrame() {
        
        initComponents();
        ImageIcon menu=new ImageIcon(getClass().getResource("/world.png"));
             this.setIconImage (menu.getImage());
              this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defaultJl3 = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();
        quitterBut = new javax.swing.JButton();
        jouerBut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jeux");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(980, 617));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(980, 617));
        setResizable(false);
        setSize(new java.awt.Dimension(980, 617));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        defaultJl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defaultsimple.png"))); // NOI18N
        defaultJl3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        defaultJl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                defaultJl3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                defaultJl3MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                defaultJl3MouseReleased(evt);
            }
        });
        getContentPane().add(defaultJl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 0, -1, -1));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExitSimple.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitMouseReleased(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(936, 0, 30, 30));

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        getContentPane().add(FrameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 980, 50));

        quitterBut.setText("Quitter");
        quitterBut.setMaximumSize(new java.awt.Dimension(59, 23));
        quitterBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterButActionPerformed(evt);
            }
        });
        getContentPane().add(quitterBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 210, 40));

        jouerBut.setText("Jouer");
        jouerBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouerButActionPerformed(evt);
            }
        });
        getContentPane().add(jouerBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 210, 40));

        jButton1.setText("Option");
        jButton1.setEnabled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 210, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuBackground.jpg"))); // NOI18N
        background.setToolTipText("");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
     int x=evt.getXOnScreen();
     int y=evt.getYOnScreen();
    this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed

    private void jouerButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouerButActionPerformed
     this.setVisible(false);
        new NiveauJFrame().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jouerButActionPerformed

    private void quitterButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterButActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_quitterButActionPerformed

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered

        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/exitnt.png"));
        Exit.setIcon(exitIcon);
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited

        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/ExitSimple.png"));
        Exit.setIcon(exitIcon);
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseReleased
        System.exit(0);
    }//GEN-LAST:event_ExitMouseReleased

    private void defaultJl3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaultJl3MouseEntered
        // TODO add your handling code here:
        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/defaultIN.png"));
        defaultJl3.setIcon(exitIcon);
    }//GEN-LAST:event_defaultJl3MouseEntered

    private void defaultJl3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaultJl3MouseExited
        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/defaultsimple.png"));
        defaultJl3.setIcon(exitIcon);
    }//GEN-LAST:event_defaultJl3MouseExited

    private void defaultJl3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaultJl3MouseReleased
        this.setExtendedState(MenuJFrame.ICONIFIED);
    }//GEN-LAST:event_defaultJl3MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JLabel background;
    private javax.swing.JLabel defaultJl;
    private javax.swing.JLabel defaultJl1;
    private javax.swing.JLabel defaultJl2;
    private javax.swing.JLabel defaultJl3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jouerBut;
    private javax.swing.JButton quitterBut;
    // End of variables declaration//GEN-END:variables
}
