/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author Mes dossiers
 */
public class QuestionJFrame extends javax.swing.JFrame {
     private int xMouse;
     private int yMouse;
     private int choix;

    public  int  getChoix() {
        return choix;
    }
   
    public JLabel getImageLbl(){
        return imageLbl;
    }
   

    public  JLabel getQuestionLbl() {
        return questionLbl;
        
    }
   

    /**
     * Creates new form jouer
     */
    public  QuestionJFrame() {
        this.setVisible(false);
        initComponents();
         ImageIcon menu=new ImageIcon(getClass().getResource("/world.png"));
             this.setIconImage (menu.getImage());
              this.setLocationRelativeTo(null);
    }
 private  void existance(JCheckBox box1,JCheckBox box2,JCheckBox box3){
     if (box1.isSelected()){
         box2.setSelected(false);
         box3.setSelected(false);
     }
 }
 private void validerCheck(JCheckBox box){
     if (box.isSelected())
         button.setEnabled(true);
     else button.setEnabled(false);       
     
 }
 public   JCheckBox getBox1(){
     return Box1;
 }
 public   JCheckBox getBox2(){
     return Box2;
 }
 public   JCheckBox getBox3(){
     return Box3;
 }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Box1 = new javax.swing.JCheckBox();
        Box2 = new javax.swing.JCheckBox();
        Box3 = new javax.swing.JCheckBox();
        defaultJl2 = new javax.swing.JLabel();
        questionLbl = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        Exit6 = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();
        imageLbl = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 617));
        setUndecorated(true);
        getContentPane().setLayout(null);

        Box1.setBackground(new java.awt.Color(153, 255, 153));
        Box1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Box1.setForeground(new java.awt.Color(255, 255, 255));
        Box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box1ActionPerformed(evt);
            }
        });
        getContentPane().add(Box1);
        Box1.setBounds(360, 230, 260, 30);

        Box2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Box2.setForeground(new java.awt.Color(255, 255, 255));
        Box2.setText("ess2");
        Box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2ActionPerformed(evt);
            }
        });
        getContentPane().add(Box2);
        Box2.setBounds(360, 280, 260, 25);

        Box3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Box3.setForeground(new java.awt.Color(255, 255, 255));
        Box3.setText("ess3");
        Box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box3ActionPerformed(evt);
            }
        });
        getContentPane().add(Box3);
        Box3.setBounds(360, 330, 260, 25);

        defaultJl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defaultsimple.png"))); // NOI18N
        defaultJl2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        defaultJl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                defaultJl2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                defaultJl2MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                defaultJl2MouseReleased(evt);
            }
        });
        getContentPane().add(defaultJl2);
        defaultJl2.setBounds(897, -1, 30, 30);

        questionLbl.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        questionLbl.setForeground(new java.awt.Color(255, 255, 255));
        questionLbl.setText("omar");
        getContentPane().add(questionLbl);
        questionLbl.setBounds(240, 80, 470, 60);

        button.setText("valider");
        button.setEnabled(false);
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button);
        button.setBounds(450, 373, 80, 30);
        button.getAccessibleContext().setAccessibleDescription("");

        Exit6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExitSimple.png"))); // NOI18N
        Exit6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Exit6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit6MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Exit6MouseReleased(evt);
            }
        });
        getContentPane().add(Exit6);
        Exit6.setBounds(935, -2, 30, 30);

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        getContentPane().add(FrameDrag);
        FrameDrag.setBounds(0, 0, 980, 40);

        imageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Allemagne.png"))); // NOI18N
        getContentPane().add(imageLbl);
        imageLbl.setBounds(60, 230, 110, 66);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuestionBackground.png"))); // NOI18N
        background.setText("12");
        getContentPane().add(background);
        background.setBounds(0, -10, 980, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2ActionPerformed
        // TODO add your handling code here:
        validerCheck(Box2);
         existance(Box2,Box1,Box3);
        if  (NiveauJFrame.getNv1().getQuestion().getNbr()==2)
            choix=1;
        else choix=0;
         
    }//GEN-LAST:event_Box2ActionPerformed

    private void Box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box1ActionPerformed
        // TODO add your handling code here:
        validerCheck(Box1);
        existance(Box1,Box2,Box3);
        if  (NiveauJFrame.getNv1().getQuestion().getNbr()==1)
            choix=1;
        else choix=0;
    }//GEN-LAST:event_Box1ActionPerformed

    private void Box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box3ActionPerformed
        // TODO add your handling code here:
          validerCheck(Box3);
         existance(Box3,Box1,Box2);
         if  (NiveauJFrame.getNv1().getQuestion().getNbr()==3)
            choix=1;
         else choix=0;
    }//GEN-LAST:event_Box3ActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
    this.setVisible (false); 
   if (NiveauJFrame.getNv1().getN() <=NiveauJFrame.getNv1().getNbrq()-2){
        NiveauJFrame.getNv1().affichage();
   }
   else  { NiveauJFrame.getNv1().score();
   
   }     
    }//GEN-LAST:event_buttonActionPerformed

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        // TODO add your handling code here:
      int x=evt.getXOnScreen();
     int y=evt.getYOnScreen();
    this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed

    private void defaultJl2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaultJl2MouseEntered
        // TODO add your handling code here:
        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/defaultIN.png"));
        defaultJl2.setIcon(exitIcon);
    }//GEN-LAST:event_defaultJl2MouseEntered

    private void defaultJl2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaultJl2MouseExited
        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/defaultsimple.png"));
        defaultJl2.setIcon(exitIcon);
    }//GEN-LAST:event_defaultJl2MouseExited

    private void defaultJl2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaultJl2MouseReleased
        this.setExtendedState(MenuJFrame.ICONIFIED);
    }//GEN-LAST:event_defaultJl2MouseReleased

    private void Exit6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit6MouseReleased
        System.exit(0);
    }//GEN-LAST:event_Exit6MouseReleased

    private void Exit6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit6MouseExited

        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/ExitSimple.png"));
        Exit6.setIcon(exitIcon);
    }//GEN-LAST:event_Exit6MouseExited

    private void Exit6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit6MouseEntered

        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/exitnt.png"));
        Exit6.setIcon(exitIcon);
    }//GEN-LAST:event_Exit6MouseEntered
 
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Box1;
    private javax.swing.JCheckBox Box2;
    private javax.swing.JCheckBox Box3;
    private javax.swing.JLabel Exit6;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JLabel background;
    private javax.swing.JButton button;
    private javax.swing.JLabel defaultJl2;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JLabel questionLbl;
    // End of variables declaration//GEN-END:variables
}
